### PR TITLE
Jekyll & persistent deploy script statuses

### PR DESCRIPTION
**Pull request by danielduhh**
- Added Jekyll
- Created persistent status.json (with status utility /api/utilities/status.js) in /opt/data/deployments directory that is update each time status changes.. status.json is read from file on server start 
- Each of the following scripts's can be executed from the posm-admin console:
  posm-deploy-full.sh
  omk-atlas.js
  render-db.update

TODO:
Kill scripts with "Cancel" button

### CODE REVIEW

**Comment by hallahan** [comment]
This looks great! For some reason, however, I'm not getting any console output when I initiate a full deploy. Debugging...

**Comment by danielduhh** [comment]
Make sure you cd into /Jekyll and Jekyll build --watch; I always forget

**Comment by danielduhh** [comment]
As well as npm install, added a couple libraries

**Comment by hallahan** [comment]
The Jekyll output is not enough?

**Comment by danielduhh** [comment]
Another thing; Webstorm was weird about automatically uploading changes to the posm; so I had to right click the /build folder and hit, "upload to posm" after making changes

**Comment by hallahan** [comment]
I checked out the HEAD of the jekyll branch both on my Mac and the POSM. I shouldn't have to rebuild the jekyll project to have things in the right state.

In the debugger, for `full-deploy.js`, it get's to that initial 'Doing a full deployment starting with fetching a HOT Export tar.gz.' response, but we never get to the callback from `fullDeployProc`.

**Comment by hallahan** [comment]
Yay, I'm getting this

```
Error: spawn EACCES
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at init (/opt/admin/posm-admin/api/controllers/full-deploy.js:53:26)
    at Layer.handle [as handle_request] (/opt/admin/posm-admin/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/admin/posm-admin/node_modules/express/lib/router/route.js:131:13)
    at next (/opt/admin/posm-admin/node_modules/express/lib/router/route.js:125:14)
    at Route.dispatch (/opt/admin/posm-admin/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/admin/posm-admin/node_modules/express/lib/router/layer.js:95:5)
    at /opt/admin/posm-admin/node_modules/express/lib/router/index.js:277:22
```

Stupid permissions. I'll sort it out and have it fixed in `posm-build` so you don't have to deal with it next time.

**Comment by hallahan** [comment]
It's there. I think for some reason the files checked in git didn't have executable permission?

https://github.com/AmericanRedCross/posm-build/blob/b4db4c1c438fc2c1d67ed4e31444de6650418339/kickstart/scripts/admin-deploy.sh#L44

**Comment by hallahan** [comment]
https://github.com/AmericanRedCross/posm-admin/commit/fec5f6ef7496b37e0b8fbacd58405c3bcc4c866a

**Pull request merged**
